export const siteConfig = {
  name: 'SPARKLINE',
  tagline: 'Spark the Change, Illuminate Success.',
  taglineFr: 'Déclenchez le changement, illuminez le succès.',
  description:
    'SPARKLINE est une agence innovante de transformation digitale créant des solutions sur mesure et stratégiques qui métamorphosent les ambitions en expériences numériques puissantes et durables.',
  url: 'https://sparkline.sn',
  ogImage: 'https://sparkline.sn/images/brand/sparkline-logo.png',
  contact: {
    phone: '+221 78 528 63 30',
    email: 'sparkline221@gmail.com',
    website: 'https://sparkline.sn',
  },
  socials: {
    linkedin: 'https://linkedin.com/company/sparkline-sn',
    instagram: 'https://instagram.com/sparkline_sn',
    twitter: 'https://twitter.com/sparkline_sn',
    facebook: 'https://facebook.com/sparkline.sn',
    youtube: 'https://youtube.com/@sparkline_sn',
  },
  keywords: [
    'transformation digitale',
    'développement web',
    'développement mobile',
    'design UI UX',
    'stratégie digitale',
    'identité visuelle',
    'branding',
    'agence digitale',
    'Sénégal',
    'Afrique',
    'innovation',
    'technologie',
    'SPARKlearn',
  ],
  authors: [{ name: 'SPARKLINE', url: 'https://sparkline.sn' }],
  creator: 'SPARKLINE',
  themeColor: '#EB4604',
} as const
