export const siteConfig = {
  name: 'SPARKLINE',
  tagline: 'Spark the Change, Illuminate Success.',
  taglineFr: 'Déclenchez le changement, illuminez le succès.',
  description:
    'SPARKLINE est une agence innovante de transformation digitale créant des solutions sur mesure et stratégiques qui métamorphosent les ambitions en expériences numériques puissantes et durables.',
  url: 'https://sparkline.sn',
  ogImage: 'https://sparkline.sn/images/brand/sparkline-logo.png',
  contact: {
    phone: '+221 78 942 24 23',
    email: 'sparkline221@gmail.com',
    website: 'https://sparkline.sn',
  },
  socials: {
    linkedin: 'https://www.linkedin.com/in/sparkline-/',
    instagram: 'https://www.instagram.com/sparkline221?igsi=MWhuYWI4anZ2d3pqdQ==',
    facebook: 'https://www.facebook.com/profile.php?id=61571444070883',
  },
  keywords: [
    'transformation digitale',
    'développement web',
    'développement mobile',
    'design UI UX',
    'stratégie digitale',
    'identité visuelle',
    'branding',
    'agence digitale',
    'Sénégal',
    'Afrique',
    'innovation',
    'technologie',
    'SPARKlearn',
  ],
  authors: [{ name: 'SPARKLINE', url: 'https://sparkline.sn' }],
  creator: 'SPARKLINE',
  themeColor: '#EB4604',
} as const
